### ISSUE TITLE
more hints for the article

### ISSUE THREAD

**Issue by nschloe** [krober10nd/SeismicMesh#139]
Important:
* You speak of "modifications of distmesh". What modifications are these, exactly? Please go into more detail in the article. (If the mods aren't too small.) If the mods are small, don't mention them.
* I think you need to make clearer that SeismicMesh is a parellel distmesh implementation plus a mesh density function generator. I would like to hear _why_ distmesh_ and not some other algorithm? Easy to implement, known to produce high-quality cells, easily paralellizable, but can be slow.
* Why don't you simply use Gmsh, right? Aha, you find that Gmsh is slow for your use case! Why? Because your density function is so complicated and it heavily benefits from vectorization. Gmsh's algorithm doesn't allow for vectorization, distmesh does. ==> For complicated density functions, distmesh is better.

Less important:
* You're using Gmsh and CGAL (perhaps others) in texttt as if it was on a command line. The names are Gmsh and CGAL, really, no particular style needed.

**Comment by krober10nd** [comment]
Awesome, thank you for the hints. 👍

**Comment by krober10nd** [comment]
Okay lets break these comments down:

> You speak of "modifications of distmesh". What modifications are these, exactly? Please go into more detail in the article. (If the mods aren't too small.) If the mods are small, don't mention them.

Okay fair enough. I'll remove "modifications". Although I meant that the parallelism was never really an option in the `DistMesh` so it's a modification to the algorithm to support parallelism. 

> I think you need to make clearer that SeismicMesh is a parellel distmesh implementation plus a mesh density function generator. I would like to hear why distmesh_ and not some other algorithm? 

Proposed new summary:

# Summary

`SeismicMesh` is a Python package containing a parallel triangular mesh generator and mesh sizing function creator for  two and three dimensional domains such as those encountered in seismology.  C++ code is wrapped with Python for performance without losing ease-of-use. Mesh generation is performed in either serial or using distributed memory parallelism with an implementation of `DistMesh` [@doi:10.1137/S0036144503429121; @peterka2014high]. `DistMesh`  is an uncomplicated algorithm that is known to produce high-quality cells, can be easily parallelized, and does not require explicit domain geometry information, which can be useful for people unfamiliar with mesh generation. Our implementation uses the Computational Geometry Algorithms Library [@cgal:hs-chdt3-20a] to perform many geometric operations quickly. 

I'm thinking about how to revise the `Statement of Need` to incorporate your other suggestions.

**Comment by nschloe** [comment]
I tried to make it a bit more crisp (feel free to use or dismiss):

SeismicMesh is a Python package for simplex mesh generation in two or three dimensions. As an implementation of DistMesh [@doi:10.1137/S0036144503429121; @peterka2014high], it produces high-quality meshes at the expense of speed. For increased efficiency, the core package is written in C++, works in parallel, and uses the Computational Geometry Algorithms Library [@CGAL:hs-chdt3-20a]. SeismicMesh can also produce mesh-density functions from seismological data to be used in the mesh generator.

**Comment by krober10nd** [comment]
That's excellent, thank you Nico.

**Comment by krober10nd** [comment]
This paragraph is a little more challenging for me, but I think it's better below. I think the point you make is quite interesting about querying sizing functions. 

 Besides that it would be nice to perhaps highlight the implicit functions that I use make the geometry creation a lot easier than hand drawing an STL. I haven't yet determined where best to put that or if I will put that in.

> Why don't you simply use Gmsh, right? Aha, you find that Gmsh is slow for your use case! Why? Because your density function is so complicated and it heavily benefits from vectorization. Gmsh's algorithm doesn't allow for vectorization, distmesh does. ==> For complicated density functions, distmesh is better.


The success of many finite element methods in geophysics hinges on the creation of a quality mesh. Despite the fact that many mesh generation programs exist such as Gmsh and CGAL, it is rare to find the capabilities to incorporate geophysical data directly into the mesh generation process in order to size elements and thus automatic mesh generation remains an unsolved problem. 

Recently, some packages have been created to this end to script mesh generation from geophysical datasets such as in coastal ocean modeling [e.g., @roberts2019oceanmesh2d; GMT and Terreno @gorman2008systematic] and reservoir modeling [e.g., MeshIT @cacace2015meshit]. Following in a similar direction to those programs, the aim of this package is to provide a simple-to-use Python package to script mesh generation from geophysical datasets by building complex mesh density function directly from seismic velocity models.

Our mesh density functions can be used with other mesh generators, however their usage can have significant implications on mesh generation performance. For example, Gmsh's advancing front and Delaunay refinement methods construct the mesh incrementally and do not permit vectorization leading to significant slow downs at scale in 2D/3D. In contrast, the DistMesh algorithm takes advantage of vectorization when querying the mesh density function and makes it a good choice for this kind of meshing problem.

**Comment by krober10nd** [comment]
Okay, I did several iterations of the above and liked how it flowed. I also rewrote the performance section to rewrite the improved 2D minimum cell qualities.

**Comment by krober10nd** [comment]
Do you have any more comments on this article @nschloe ? The latest paper is on the main branch.

**Comment by krober10nd** [comment]
@nschloe Can we close this issue?

**Comment by nschloe** [comment]
I will check as soon as I have time.

**Comment by krober10nd** [comment]
thanks

**Comment by nschloe** [comment]
Okay, closing.
